services:
  db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - group-project:/var/lib/postgresql
      - ./src/init_data:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPass #TODO: temp, change here and in .env
      - POSTGRES_DB=testName
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'sh -c "npm install && npm start"' #TODO: change to `npm run testandrun` to run mocha
volumes:
  group-project:
